language: php
sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

php: 7.1

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - DOCKER_API_VERSION=V1_33 DOCKER_VERSION=17.10.0~ce-0~ubuntu
    - DOCKER_API_VERSION=V1_32 DOCKER_VERSION=17.09.0~ce-0~ubuntu
    - DOCKER_API_VERSION=V1_31 DOCKER_VERSION=17.07.0~ce-0~ubuntu
    - DOCKER_API_VERSION=V1_30 DOCKER_VERSION=17.06.2~ce-0~ubuntu
    - DOCKER_API_VERSION=V1_29 DOCKER_VERSION=17.05.0~ce-0~ubuntu-trusty
    - DOCKER_API_VERSION=V1_28 DOCKER_VERSION=17.04.0~ce-0~ubuntu-trusty
    - DOCKER_API_VERSION=V1_27 DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty
    - DOCKER_API_VERSION=V1_26 DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty
    - DOCKER_API_VERSION=V1_25 DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 7.0
      sudo: required
      services:
          - docker
      env: DOCKER_API_VERSION=V1_25 DOCKER_VERSION=17.03.2~ce-0~ubuntu-trusty COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci"
    - php: 7.2
      sudo: required
      services:
          - docker
      env: DOCKER_API_VERSION=V1_33 DOCKER_VERSION=17.10.0~ce-0~ubuntu

before_install:
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-ce=${DOCKER_VERSION}
  - travis_retry composer self-update

install:
  - travis_retry composer install
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - $TEST_COMMAND

after_success:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi

after_script:
  - sudo cat /var/log/upstart/docker.log
